name: Create release
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Create release commit
        run: |
          make dch
          sed -i "s/UNRELEASED/stable/" debian/changelog
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add debian/changelog
          git commit -m "Release $(dpkg-parsechangelog -S Version)"
      - name: Test
        run: |
          make test
      - name: Push
        run: |
          git push
